Desktop version page
Ejikeokegbe/Mobile-First-portifolio pull request #4
Opened 2023-05-11 15:19 UTC by Ejikeokegbe

Added some Figma templates for more portfolio description
Added some features to enable desktop display on mobile first website
This shows the power of media queries on making a website responsive

2023-05-11 16:27 UTC, Shisui6 requested changes
Hi @Ejikeokegbe, 

# Requires Changes 🍀
You have done a great job so far!👏👏
You still need to work on a few issues before moving on to the next project, but you're almost there🪲!

## Highlights🎯
- Good use of media queries ✅


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🪶
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

- Please remove the FAQ section from your readme file since it is not being used. This will make your readme look more professional

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 16:27 UTC, Shisui6 commented on style.css
> +  font-family: Poppins, sans-serif;
Currently, your fonts are not being applied in the browser. Please make sure that you are importing and using the correct font family used in the figma template then update **all** your text elements to use the correct font family🙏

2023-05-11 16:27 UTC, Shisui6 commented on style.css
> +  }
The styles you applied to your desktop version are rearranging the content in the works section of your mobile version, as seen in the screenshots below:

Your design:
<img width="242" alt="image" src="https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/37116322/acc0d5c7-d185-4c7e-b082-679561d838e6">

Figma design:
<img width="214" alt="image" src="https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/37116322/5f5db438-4af2-47c3-9de8-6a6e8b2a68ec">

Please make your that your mobile version is unaffected by your desktop styling🙏

2023-05-11 16:27 UTC, Shisui6 commented on style.css
> +  }
Please resize the background image on your headline section to match the figma design better. Currently, the image is stretched.

Your design:
<img width="507" alt="image" src="https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/37116322/d82227b3-a4cd-4f64-82eb-cddbe4ba75ae">

Figma design:
<img width="542" alt="image" src="https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/37116322/81f8d860-8981-437a-99d3-8709c56a9033">

2023-05-11 16:27 UTC, Shisui6 commented on style.css
> +  }
Kindly update your works section to match the figma design better🙏

Your design:
<img width="512" alt="image" src="https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/37116322/5aeda4af-aad0-4968-9d18-6273dc398f30">

Figma design:
<img width="492" alt="image" src="https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/37116322/8fb7485c-17ac-4c36-8fbe-813309c56feb">

A few things to note:
- Please reduce the left and right margins on each card
- Please reduce the left and right padding on each card
- Please increase the size of the image to match the figma design
- Please reduce the height of the text content so it doesn't span the full height of the card and matches the design

2023-05-11 16:27 UTC, Shisui6 commented on style.css
> +  }
Kindly update your about section to match the figma design better🙏

Your design:
<img width="507" alt="image" src="https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/37116322/20c3b1af-9ca0-4b6d-b804-c36a92cbcb87">

Figma design:
<img width="493" alt="image" src="https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/37116322/e6297345-8f5d-4f59-a2f3-09b34416700e">

A few things to note:
- Please increase the spacing between the elements on the left-hand side
- Please update the color of the `let's connect` heading
- Please increase the spacing between the technologies (HTML, CSS, JS)

2023-05-11 16:27 UTC, Shisui6 commented on style.css
> +}
Kindly update the styling of your contact section to match the figma design better🙏

Your design:
<img width="509" alt="image" src="https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/37116322/6de8df39-5dec-407f-a896-94e7770e485d">

Figma design:
<img width="492" alt="image" src="https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/37116322/87281772-e7d2-4088-8ab9-3c8beb4f7ba2">

A few things to note:
- Please resize the background image so it matches the figma design
- Please remove the border radius on the input fields on the desktop version

2023-05-12 16:18 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @Ejikeokegbe 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 16:18 UTC, tresorsawasawa commented on style.css
>  }
- [ ] As mentioned by the previous reviewer and for the project requirements to match your Headline section design to the one from Figma design, kindly ensure that you use the correct `text-color` on your heading and leading text. Here are the correct colors to be used: `#091e42` on the `Heading` and `#344563` on the `leadding` text. 
**Make sure you apply this on both Mobile and Desktop**

2023-05-12 16:18 UTC, tresorsawasawa commented on index.html
>          <div class="about-div">
- [ ] As mentioned by the previous reviewer to stick as much as possible to Figma design, I think there are things should improve again such as the `fonts(size, weight,...)`, `color` on some text, `spacing`(padding or margin), `alignment`,...
Just take a look on the difference on the above 2 images:
### Figma Design 
![Screenshot from 2023-05-12 17-57-57](https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/83042742/e1cb4998-fca7-4fd6-a432-81f1e73281e7)

### Your Design 
![Screenshot from 2023-05-12 18-17-39](https://github.com/Ejikeokegbe/Mobile-First-portifolio/assets/83042742/09977bf7-74fa-4c98-bfd3-00988d4dabc9)

2023-05-12 16:18 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @Ejikeokegbe 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 18:52 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @Ejikeokegbe, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://camo.githubusercontent.com/5f6b955314ad7a8c010bb5de56877a2fa40a6d2bc5aeabd629e6a150f73afd97/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966" width="375px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] GitHub flow is used correctly :white_check_mark:  
- [x] Implemented changes requested by the previous reviewer :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark:   

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 14:48 UTC, merged